# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\code\pyqt\ftp\server.ui'
#
# Created: Sun Dec 16 17:14:37 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Server(object):
    def setupUi(self, Server):
        Server.setObjectName(_fromUtf8("Server"))
        Server.setWindowModality(QtCore.Qt.ApplicationModal)
        Server.resize(470, 280)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Server.sizePolicy().hasHeightForWidth())
        Server.setSizePolicy(sizePolicy)
        Server.setMinimumSize(QtCore.QSize(470, 280))
        Server.setMaximumSize(QtCore.QSize(470, 280))
        Server.setBaseSize(QtCore.QSize(470, 282))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon/designer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Server.setWindowIcon(icon)
        Server.setSizeGripEnabled(False)
        Server.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Server)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Server)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 431, 231))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.server_name = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.server_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.server_name.setObjectName(_fromUtf8("server_name"))
        self.horizontalLayout_8.addWidget(self.server_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.platform = QtGui.QComboBox(self.verticalLayoutWidget)
        self.platform.setMinimumSize(QtCore.QSize(160, 0))
        self.platform.setMaximumSize(QtCore.QSize(160, 16777215))
        self.platform.setObjectName(_fromUtf8("platform"))
        self.horizontalLayout_6.addWidget(self.platform)
        self.add_platform = QtGui.QToolButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icon/0949090.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_platform.setIcon(icon1)
        self.add_platform.setObjectName(_fromUtf8("add_platform"))
        self.horizontalLayout_6.addWidget(self.add_platform)
        self.edit_platform = QtGui.QToolButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icon/09490944.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_platform.setIcon(icon2)
        self.edit_platform.setObjectName(_fromUtf8("edit_platform"))
        self.horizontalLayout_6.addWidget(self.edit_platform)
        self.delete_platform = QtGui.QToolButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icon/0949091.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_platform.setIcon(icon3)
        self.delete_platform.setObjectName(_fromUtf8("delete_platform"))
        self.horizontalLayout_6.addWidget(self.delete_platform)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.host = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.host.setObjectName(_fromUtf8("host"))
        self.horizontalLayout.addWidget(self.host)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.port = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.port.setObjectName(_fromUtf8("port"))
        self.horizontalLayout.addWidget(self.port)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.path = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.path.setObjectName(_fromUtf8("path"))
        self.horizontalLayout_7.addWidget(self.path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.account = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.account.setObjectName(_fromUtf8("account"))
        self.horizontalLayout_3.addWidget(self.account)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.password = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_5.addWidget(self.password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.save = QtGui.QPushButton(self.verticalLayoutWidget)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_2.addWidget(self.save)
        self.cancel = QtGui.QPushButton(self.verticalLayoutWidget)
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.horizontalLayout_2.addWidget(self.cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Server)
        QtCore.QObject.connect(self.cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Server.close)
        QtCore.QMetaObject.connectSlotsByName(Server)

    def retranslateUi(self, Server):
        Server.setWindowTitle(QtGui.QApplication.translate("Server", "服务器", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Server", "添加", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Server", "名称：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Server", "平台：", None, QtGui.QApplication.UnicodeUTF8))
        self.add_platform.setToolTip(QtGui.QApplication.translate("Server", "<html><head/><body><p>添加平台</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.add_platform.setText(QtGui.QApplication.translate("Server", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_platform.setToolTip(QtGui.QApplication.translate("Server", "<html><head/><body><p>编辑选中平台名称</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_platform.setText(QtGui.QApplication.translate("Server", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_platform.setToolTip(QtGui.QApplication.translate("Server", "<html><head/><body><p>删除选中平台</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_platform.setText(QtGui.QApplication.translate("Server", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Server", "主机：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Server", "端口：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Server", "路径：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Server", "账号：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Server", "密码：", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("Server", "保 存", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("Server", "取 消", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Server = QtGui.QDialog()
    ui = Ui_Server()
    ui.setupUi(Server)
    Server.show()
    sys.exit(app.exec_())

